language: c
sudo: required

env:
  - OCAML_VERSION=4.09 Z3_VERSION=4.8.1
  - OCAML_VERSION=4.09 Z3_VERSION=4.8.4
  - OCAML_VERSION=4.09 Z3_VERSION=4.8.6
  - OCAML_VERSION=4.09 Z3_VERSION=4.8.7
  - OCAML_VERSION=4.10 Z3_VERSION=4.8.1
  - OCAML_VERSION=4.10 Z3_VERSION=4.8.4
  - OCAML_VERSION=4.10 Z3_VERSION=4.8.6
  - OCAML_VERSION=4.10 Z3_VERSION=4.8.7
  
os:
  - linux
  - osx

cache:
  directories:
    - $HOME/.opam
  
before_install:
  - bash -ex .travis-ocaml.sh
  - opam install -y dune
  - opam repo add ivg git@github.com:ivg/opam-repository.git
  - opam install -y -v z3=${Z3_VERSION}
 
script:
  - Z3_LIB="$(opam var lib)/z3"
  - LD_LIBRARY_PATH="${Z3_LIB}:${LD_LIBRARY_PATH}"; export LD_LIBRARY_PATH
  - if [ "${Z3_VERSION}" = "4.8.1" ] && [ "${TRAVIS_OS_NAME}" = "osx" ]; then DYLD_FALLBACK_LIBRARY_PATH="${Z3_LIB}:${DYLD_FALLBACK_LIBRARY_PATH}"; export DYLD_FALLBACK_LIBRARY_PATH; fi
  - export -p | grep LIBRARY_PATH
  - opam exec -- dune build --verbose basic.exe logic.exe
  - opam exec -- dune runtest
  
  
