lang: c
sudo: required

env:
  - OCAML_VERSION=4.09 Z3_VERSION=4.8.1
  - OCAML_VERSION=4.09 Z3_VERSION=4.8.4
  - OCAML_VERSION=4.09 Z3_VERSION=4.8.6
  - OCAML_VERSION=4.09 Z3_VERSION=4.8.7
  
os:
  - linux
  - osx

before_install:
  - bash -ex .travis-ocaml.sh
  - opam install -y dune
  - opam install -y -v z3=${Z3_VERSION}
 
script:
  - LD_LIBRARY_PATH="$(opam var lib)/z3:${LD_LIBRARY_PATH}"
  - export LD_LIBRARY_PATH
  - opam exec -- dune build --verbose basic.exe logic.exe
  - opam exec -- dune runtest
  
  
